### ISSUE TITLE
Warning and error for the example data

### ISSUE THREAD

**Issue by yewero** [lanagarmire/deepimpute#15]
```
Normalization
WARNING:tensorflow:From /XXX/install/lib/python3.6/site-packages/deepimpute/multinet.py:211: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

2019-11-28 16:02:22.399361: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
Building network
```

**Comment by Puumanamana** [comment]
Hi,

Thanks for your PR. I merged it with master.
Was the problem fixed with your PR allowing for GPUs?

**Comment by yewero** [comment]
My PR didn't fix this warning and error.
I ran the example on a computer with CPUs but without GPUs.

**Comment by Puumanamana** [comment]
Which version of TensorFlow are you using?

**Comment by yewero** [comment]
1.15.0-rc1

**Comment by Puumanamana** [comment]
So, if I understand correctly, the code runs fine with a computer without GPUs, but not if there are some?
On the computer where it failed, did you try to see if TensorFlow works? For instance, does this work?
```python
import tensorflow as tf 

hello = tf.constant('Hello, TensorFlow!') 
sess = tf.Session() 
print(sess.run(hello))
```

**Comment by yewero** [comment]
```
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
```

> 2019-12-02 15:06:24.691005: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /XXX/install/lib
> 2019-12-02 15:06:24.691069: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
> 2019-12-02 15:06:24.691120: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (halo): /proc/driver/nvidia/version does not exist
> 2019-12-02 15:06:24.705297: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2599980000 Hz
> 2019-12-02 15:06:24.710359: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4611210 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2019-12-02 15:06:24.710393: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version

`print(sess.run(hello))`
b'Hello, TensorFlow!'

**Comment by Puumanamana** [comment]
It seems your CUDA installation is not working properly or you could be missing some Nvidia libraries. The easiest would be to just install `tensorflow` without GPU support.

Otherwise, you should be able to find information on how to correctly install cuda on [TensorFlow website](https://www.tensorflow.org/install/gpu).
If it still won't work, you should be able to find some related issues, maybe [here](https://github.com/tensorflow/tensorflow/issues/19266) or [here](https://ubuntuforums.org/showthread.php?t=2383261).

**Comment by yewero** [comment]
Thanks.
But how to install tensorflow without GPU support?

**Comment by Puumanamana** [comment]
Oh I thought you had installed `tensorflow-gpu` with pip.
Looking at this [other issue](https://stackoverflow.com/questions/44552585/prevent-tensorflow-from-accessing-the-gpu), maybe you could try:
```bash 
# Run in your terminal
> export CUDA_VISIBLE_DEVICES=-1
> python run_test.py
```
and then see if you still have the error. Otherwise, this might work too:
```python
sess = tf.Session(config=tf.ConfigProto(device_count={'GPU': 0}))
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))
```

Let me know if any of those work, I could add an option to `deepImpute` to exclude GPUs. Unfortunately, I don't have access to GPUs right now, so I can't test it.

**Comment by yewero** [comment]
Sorry but where is `run_test.py`?

**Comment by Puumanamana** [comment]
Oh I forgot to mention it. I called `run_test.py` the little "Hello, Tensorflow" script
